### PR TITLE
Stop printing help menu on unknown command

### LINKED ISSUE #204: Don't print help automatically on unknown command
This is a design fault that I introduced - bots should instead say "Unknown command - use `!moderator help` for help" when someone issues an incorrect command. The explicit help command then prints the full help.

Otherwise this happens:
image

### PR DESCRIPTION
**Pull request by H-Shay**
while I was in the area, make the help menu a little more manageable by grouping related commands. I couldn't fit all of the new menu into a screenshot, but the gist of it is:
mjolnir_help

Areas are:
- Protection Actions/Options
- Moderation Actions
- Policy List Options/Actions
- Room Managment
- Bot Status and Management

Fixes #204 and #52

### CODE REVIEW

File: src/commands/CommandHandler.ts [hunk 1]
```diff
@@ -185,20 +199,25 @@ export async function handleCommand(roomId: string, event: { content: { body: st
...
+            const botMenu =
+                "" +
+                "!mjolnir                                                            - Print status information\n" +
+                "!mjolnir status                                                     - Print status information\n" +
+                "!mjolnir verify                                                     - Ensures Mjolnir can moderate all your rooms\n" +
                 "!mjolnir help                                                       - This menu\n";
-            const html = `<b>Mjolnir help:</b><br><pre><code>${htmlEscape(menu)}</code></pre>`;
-            const text = `Mjolnir help:\n${menu}`;
+
+            const html = `<h3>Mjolnir help menu:</h3><br><b>Protection Actions/Options:</b><pre><code>${htmlEscape(protectionMenu)}</code></pre><br><b>Moderation Actions:</b><pre><code>${htmlEscape(actionMenu)}</code></pre><br><b>Policy List Options/Actions:</b><pre><code>${htmlEscape(policyListMenu)}</code></pre><br><b>Room Managment:</b><pre><code>${htmlEscape(roomsMenu)}</code></pre><br><b>Bot Status and Management:</b><pre><code>${htmlEscape(botMenu)}</code></pre>`;
```
Comment (turt2live) [inline src/commands/CommandHandler.ts:211]: non-blocking: fwiw, the tilde character strings support newlines to retain formatting. For plaintext this is somewhat of an issue, but for HTML the extra whitespace doesn't affect anything. To make this a bit easier to read we can add a bunch of newlines:
```suggestion
            const html = `<h3>Mjolnir help menu:</h3><br>
            <b>Protection Actions/Options:</b><pre><code>${htmlEscape(protectionMenu)}</code></pre><br>
            <b>Moderation Actions:</b><pre><code>${htmlEscape(actionMenu)}</code></pre><br>
            <b>Policy List Options/Actions:</b><pre><code>${htmlEscape(policyListMenu)}</code></pre><br>
            <b>Room Managment:</b><pre><code>${htmlEscape(roomsMenu)}</code></pre><br>
            <b>Bot Status and Management:</b><pre><code>${htmlEscape(botMenu)}</code></pre>`;
```

The linter may have opinions on my formatting here.

(also `<br />` should be self-closing, like so)

**Review by turt2live — APPROVED** [review]
thanks!
